services:
  - type: web
    name: job-seeker-toolkit
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm ci && npm run build
    startCommand: node server/server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: ALLOWED_ORIGIN
        value: https://your-app.onrender.com

